name: 'ros2-deb-build'

inputs:
  distro:
    required: false
    default: 'humble'

outputs:
  archives:
    value: ${{ steps.build.outputs.archives }}

runs:
  using: 'composite'
  steps:
    - run: |
        cd $(mktemp -d)
        cp -R $GITHUB_ACTION_PATH/* .
        m4 -DDISTRO=${{ inputs.distro }} Dockerfile.m4 > Dockerfile
        docker build -t ros2-deb-build .
      shell: bash

    - id: build
      run: |
        ARCHIVES=$(mktemp -d)
        docker run -v $(pwd):/workspace -v $ARCHIVES:/archives ros2-deb-build
        echo "archives=$(echo $ARCHIVES)" >> $GITHUB_OUTPUT
      shell: bash
